# Generated by Django 4.1.7 on 2023-04-26 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='varify',
        ),
    ]
