# Generated by Django 4.0.3 on 2023-06-15 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_varify_mail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addhouse',
        ),
    ]
