# Generated by Django 4.0.3 on 2023-06-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_addhouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='addhouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=50)),
                ('owner_contect_number', models.CharField(max_length=15)),
                ('house_type', models.ImageField(upload_to='')),
                ('rent', models.CharField(max_length=20)),
                ('house_facing', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=30)),
                ('conditions', models.CharField(max_length=200)),
                ('Facilities', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=30)),
                ('picture1', models.FileField(upload_to='HousePictures')),
                ('picture2', models.FileField(upload_to='HousePictures')),
                ('picture3', models.FileField(upload_to='HousePictures')),
            ],
        ),
    ]
