# Generated by Django 4.0.3 on 2023-06-20 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_addhouse_facilities_alter_addhouse_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activations',
            name='current_city',
        ),
    ]
